In [0]:
#DETECTS EMAIL SPAM 
# 1 = SPAM 
# 0 = NOT 
# DETECTS AND CLASSIFIES SPAM USING NATURAL LANGUAGE PROCESSING
# COUNT VECTORISER : NAIVE BAYES CLASSIFIER 


In [0]:
#Import libraries
import numpy as np 
import pandas as pd 
import nltk
from nltk.corpus import stopwords
import string
from sklearn.feature_extraction.text import CountVectorizer

In [41]:
#Load the data
from google.colab import files # Use to load data on Google Colab
uploaded = files.upload() # Use to load data on Google Colab

Saving emails.csv to emails (1).csv


In [42]:
# create df with email csv file 
df = pd.read_csv('emails.csv') #read the CSV file
df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [43]:
#Print the df shape (rows and cols)
df.shape

(5728, 2)

In [0]:
#clean data by removing any duplicates 
df.drop_duplicates(inplace = True)

In [45]:
#Show the number of missing (NAN, NaN, na) data for each column
df.isnull().sum()

text    0
spam    0
dtype: int64

In [46]:
# download NLP stop words 
# stop words = words which have very little meaning, such as "and", "the", "a", "an"
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [0]:
#tokeninisation 
# remove stopwords 
# remove punction 
# return a clean list of words for analysis
def cleaning_text(text):

# removing punctiation
  nPunc = [char for char in text if char not in string.punctuation]
  nPunc = ''.join(nPunc)
  # cleaning stop words
  clean_words = [word for word in nPunc.split() if word.lower() not in stopwords.words('english')]
  #return clean list of words 
  return clean_words

In [48]:
#show the list of tokens creted
df['text'].head().apply(cleaning_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [0]:
#import the count vectoriser - converts a text doc into a matrix of token counts 
from sklearn.feature_extraction.text import CountVectorizer

## Converts strings to integer counts
vectorizer = CountVectorizer(analyzer=cleaning_text)

## Learn a vocabulary dictionary of all tokens in the raw documents.
bow_transformer = vectorizer.fit(df['text'])    


messages_bow = CountVectorizer(analyzer=cleaning_text).fit_transform(df['text'])

In [0]:
#Split the data into 70% training (X_train & y_train) and 30% testing (X_test & y_test) data sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(messages_bow, df['spam'], test_size = 0.3, random_state = 0)

In [55]:
#Get the shape of messages_bow
messages_bow.shape

(5695, 37229)

In [56]:
#create and fit the naive bayes classifier 
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [58]:
#Print the predictions
print(classifier.predict(X_train))

#Print the actual values
print(y_train.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [60]:
# compare classification model on the traning set 
#show confusion matrix & accuracy
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score

pred = classifier.predict(X_train)
print(classification_report(y_train ,pred ))
print('Confusion Matrix: \n',confusion_matrix(y_train,pred))
print()
print('Accuracy: ', accuracy_score(y_train,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3022
           1       0.99      1.00      0.99       964

    accuracy                           1.00      3986
   macro avg       0.99      1.00      1.00      3986
weighted avg       1.00      1.00      1.00      3986

Confusion Matrix: 
 [[3011   11]
 [   0  964]]

Accuracy:  0.9972403411941796


In [63]:
#predictions 
print(" Predicted value based on model: ", classifier.predict(X_test))
#actual value
print('Actual value: ',y_test.values)

 Predicted value based on model:  [1 0 0 ... 0 0 1]
Actual value:  [1 0 0 ... 0 0 0]
